# training
saved_model_path: ""
log_dir: "../../models/logs"
model_path: "../../models"
train_dir: "/mnt/Vault/database"
val_dir: "/mnt/Vault/database"
# cfgs
seeds: 4414
workers: 1
batch_size: 192
num_iters: 30000
val_interval: 2000
lr: 1.
beta1: 0.9
rho: 0.95
eps: 1.E-8
grad_clip: 5

#misc
dataset: "MJ-ST"
batch_ratio: "0.5-0.5"
usage_ratio: 1.
batch_max_len: 25
height: 32
width: 100
rgb: False
character: "0123456789abcdefghijklmnopqrstuvwxyz"
pad: True
#sensitive
sensitive: True
filtering: True

# model
transform: "TPS" # others: None
backbone: "ResNet" #TODO: added RCNN
sequence: "biLSTM" # others: None
prediction: "Attention" # Others: CTC
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256
num_classes: 1000
