iter: 1

# training configs
continue: False
training: True
lr: 0.0001
SEQ_LENGTH: 47
INPUT_SIZE:
  - 200
  - 32
NUM_CLASSES: 62
NUM_BATCHES: 112884
BATCH_SIZE: 64
EPOCHS: 10

# path configs
MODEL_PATH: "../../../models"
DATA_PATH: "/mnt/Vault/database/mjsynth"
