# training
pretrained: ""
log_dir: "models/logs"
model_dir: "models"
train_root: "data/train"
val_root: "data/val"

# cfgs
seeds: 4420
workers: 2
num_gpu: 1
batch_size: 64
num_iters: 30000
val_interval: 1000
save_interval: 1000
lr: 0.01
adam: False
beta1: 0.9 # use adadelta by default
rho: 0.95
eps: 1.E-8
grad_clip: 5

#fine_tune
random_sample: True
keep_ratio: True
batch_max_len: 25
num_epochs: 25
height: 32
width: 100
rgb: False
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256
num_classes: 1000
character: "0123456789abcdefghijklmnopqrstuvwxyz"
#sensitive
filtering: True

# model
transform: "TPS" # others: None
backbone: "ResNet" #TODO: added RCNN
sequence: "biLSTM" # others: None
prediction: "Attention" # Others: CTC
