version: 2.1
jobs:
  build_and_push:
    docker:
      - image: google/cloud-sdk
    environment:
      - GOOGLE_PROJECT_ID: "lightly-backend"
      - GOOGLE_COMPUTE_ZONE: ""
      - GOOGLE_CLUSTER_NAME: ""

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: master
