---
dataset:
  - coco_text
  - synthtext
  - receipt
IMAGE_SIZE: 608
BATCH_SIZE: 2
BUFFER_SIZE: 300
NUM_CLASSES: 2
PREFETCH_SIZE: 5
LR: 1.E-3
LR_MIN: 1.E-6
WARMUP_EPOCHS: 1
TRAIN_EPOCHS: 5
yolo_score_threshold: 0.5
yolo_iou_threshold: 0.5
